---
name: Build Raspbian 12

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'images/raspbian-12/**'
      - '.github/workflows/build_container.yaml'
  # Build at noon, on the 1st and 15th of each month.
  schedule:
    - cron: '0 12 1 * *'
    - cron: '0 12 15 * *'

jobs:
  build_raspbian-12:
    uses: ./.github/workflows/build_container.yaml
    with:
      image: raspbian-12
      platforms: '["arm"]'
